name: topdown

ghc-options:
  - -Wall
  - -optl-fuse-ld=gold
  - -O2
ld-options:
  - -fuse-ld=gold

library:
  source-dirs: src
  dependencies:
    - base
    - aeson
    - array
    - bytestring
    - containers
    - generic-lens
    - hashable
    - interpolate
    - lens
    - linear
    - MonadRandom
    - mtl
    - sdl2
    - sdl2-image
    - sdl2-ttf
    - template-haskell
    - text
    - vector
  default-extensions:
    - AllowAmbiguousTypes
    - DataKinds
    - DeriveFunctor
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - RankNTypes
    - ScopedTypeVariables
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - ViewPatterns

executables:
  topdown-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - topdown
